# application.yml

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  application:
    name: product-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
